apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: knee-trainer
data:
  Caddyfile: |
    :3000 {
        root * /usr/share/caddy
        file_server
        reverse_proxy /api/* knee-trainer-api-svc.knee-trainer.svc.cluster.local
    }