apiVersion: apps/v1
kind: Deployment
metadata:
  name: knee-trainer-app-client
  namespace: knee-trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knee-trainer-app-client
      env: dev
  template:
    metadata:
      labels:
        app: knee-trainer-app-client
        env: dev
    spec:
      containers:
      - name: knee-trainer-app-client
        image: registry.moglidev.xyz/kneetrainer-app-client:dev1.2
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/caddy
          name: caddy-config
        - mountPath: /data
          name: knee-trainer-client-pvc
        - mountPath: /config
          name: knee-trainer-client-pvc
        env:
        - name: REACT_APP_API_URL
          value: knee-trainer-api-svc.knee-trainer.svc.cluster.local
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: caddy-config
        configMap:
          name: caddy-config
      - name: knee-trainer-client-pvc
        persistentVolumeClaim:
          claimName: knee-trainer-client-pvc
      imagePullSecrets:
      - name: registry-moglidev-secret

---
apiVersion: v1
kind: Service
metadata:
  name: knee-trainer-app-svc
spec:
  type: LoadBalancer
  selector:
    app: knee-trainer-app-client
    env: dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000