apiVersion: apps/v1
kind: Deployment
metadata:
  name: knee-trainer-app-client
  namespace: knee-trainer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knee-trainer-app-client
      env: dev
  template:
    metadata:
      labels:
        app: knee-trainer-app-client
        env: dev
    spec:
      containers:
      - name: knee-trainer-app-client
        image: registry.moglidev.xyz/kneetrainer-app-client:dev1.1
        ports:
        - containerPort: 3000
        # volumeMounts:
        # - mountPath: /usr/src/app
        #   name: knee-trainer-client-pvc
        env:
        - name: REACT_APP_API_URL
          value: http://knee-trainer-api-svc
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
      # volumes:
      # - name: knee-trainer-client-pvc
      #   persistentVolumeClaim:
      #     claimName: knee-trainer-client-pvc
      imagePullSecrets:
      - name: registry-moglidev-secret

---
apiVersion: v1
kind: Service
metadata:
  name: knee-trainer-app-svc
spec:
  type: LoadBalancer
  selector:
    app: knee-trainer-app-client
    env: dev
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000